In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [3]:
raw_path = Path("bloomberg_raw_etf_2010_2025.csv")
raw_path.exists()

True

In [4]:
df_raw = pd.read_csv(raw_path)
df_raw.head()

C:\Users\Zhaniya\AppData\Local\Temp\ipykernel_15744\2578083909.py:1: DtypeWarning: Columns (0: Unnamed: 1, 1: Unnamed: 2, 2: Unnamed: 3, 3: Unnamed: 4, 4: Unnamed: 7, 5: Unnamed: 8, 6: Unnamed: 9, 7: Unnamed: 10, 8: Unnamed: 13, 9: Unnamed: 14, 10: Unnamed: 15, 11: Unnamed: 16, 12: Unnamed: 19, 13: Unnamed: 20, 14: Unnamed: 21, 15: Unnamed: 22, 16: Unnamed: 25, 17: Unnamed: 26, 18: Unnamed: 27, 19: Unnamed: 28, 20: Unnamed: 31, 21: Unnamed: 32, 22: Unnamed: 33, 23: Unnamed: 34, 24: Unnamed: 37, 25: Unnamed: 38, 26: Unnamed: 39, 27: Unnamed: 40, 28: Unnamed: 43, 29: Unnamed: 44, 30: Unnamed: 45, 31: Unnamed: 46, 32: Unnamed: 49, 33: Unnamed: 50, 34: Unnamed: 51, 35: Unnamed: 52, 36: Unnamed: 55, 37: Unnamed: 56, 38: Unnamed: 57, 39: Unnamed: 58, 40: Unnamed: 61, 41: Unnamed: 62, 42: Unnamed: 63, 43: Unnamed: 64, 44: Unnamed: 67, 45: Unnamed: 68, 46: Unnamed: 69, 47: Unnamed: 70, 48: Unnamed: 73, 49: Unnamed: 74, 50: Unnamed: 75, 51: Unnamed: 76, 52: Unnamed: 79, 53: Unnamed: 80, 54: Unnamed: 81, 55: Unnamed: 82, 56: Unnamed: 85, 57: Unnamed: 86, 58: Unnamed: 87, 59: Unnamed: 88, 60: Unnamed: 91, 61: Unnamed: 92, 62: Unnamed: 93, 63: Unnamed: 94, 64: Unnamed: 97, 65: Unnamed: 98, 66: Unnamed: 99, 67: Unnamed: 100, 68: Unnamed: 103, 69: Unnamed: 104, 70: Unnamed: 105, 71: Unnamed: 106, 72: Unnamed: 109, 73: Unnamed: 110, 74: Unnamed: 111, 75: Unnamed: 112, 76: Unnamed: 115, 77: Unnamed: 116, 78: Unnamed: 117, 79: Unnamed: 118, 80: Unnamed: 121, 81: Unnamed: 122, 82: Unnamed: 123, 83: Unnamed: 124, 84: Unnamed: 127, 85: Unnamed: 128, 86: Unnamed: 129, 87: Unnamed: 130, 88: Unnamed: 133, 89: Unnamed: 134, 90: Unnamed: 135, 91: Unnamed: 136, 92: Unnamed: 139, 93: Unnamed: 140, 94: Unnamed: 141, 95: Unnamed: 142, 96: Unnamed: 145, 97: Unnamed: 146, 98: Unnamed: 147, 99: Unnamed: 148, 100: Unnamed: 151, 101: Unnamed: 152, 102: Unnamed: 153, 103: Unnamed: 154, 104: Unnamed: 157, 105: Unnamed: 158, 106: Unnamed: 159, 107: Unnamed: 160, 108: Unnamed: 163, 109: Unnamed: 164, 110: Unnamed: 165, 111: Unnamed: 166, 112: Unnamed: 169, 113: Unnamed: 170, 114: Unnamed: 171, 115: Unnamed: 172, 116: Unnamed: 175, 117: Unnamed: 176, 118: Unnamed: 177, 119: Unnamed: 178) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw = pd.read_csv(raw_path)

,SPY US Equity,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,QQQ US Equity,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,VIX Index,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178
0,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,...,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume
1,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN
2,04/01/2010,113.33,NaN,NaN,118944541,NaN,04/01/2010,46.42,NaN,NaN,...,17.23,17,17.35,9720405,NaN,04/01/2010,20.04,NaN,NaN,NaN
3,05/01/2010,113.63,NaN,NaN,111579866,NaN,05/01/2010,46.42,NaN,NaN,...,17.51,17.47,17.49,13324963,NaN,05/01/2010,19.35,NaN,NaN,NaN
4,06/01/2010,113.71,NaN,NaN,116074402,NaN,06/01/2010,46.14,NaN,NaN,...,17.86,17.91,18.13,14046940,NaN,06/01/2010,19.16,NaN,NaN,NaN

In [5]:
print("Shape:", df_raw.shape)
print("\nColumns:")
print(df_raw.columns.tolist())

Shape: (4175, 179)

Columns:
['SPY US Equity', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'QQQ US Equity', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'IWM US Equity', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'DIA US Equity', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'VTI US Equity', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'XLB US Equity', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'XLE US Equity', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'XLF US Equity', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'XLI US Equity', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'XLK US Equity', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'XLP US Equity', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'XLU US Equity', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71', 'XLV US Equity', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'XLY US Equity', 'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82', 'Unnamed: 83', 'XLRE US Equity', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'SHY US Equity', 'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94', 'Unnamed: 95', 'IEF US Equity', 'Unnamed: 97', 'Unnamed: 98', 'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'TLT US Equity', 'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106', 'Unnamed: 107', 'TIP US Equity', 'Unnamed: 109', 'Unnamed: 110', 'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'LQD US Equity', 'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118', 'Unnamed: 119', 'HYG US Equity', 'Unnamed: 121', 'Unnamed: 122', 'Unnamed: 123', 'Unnamed: 124', 'Unnamed: 125', 'EFA US Equity', 'Unnamed: 127', 'Unnamed: 128', 'Unnamed: 129', 'Unnamed: 130', 'Unnamed: 131', 'EEM US Equity', 'Unnamed: 133', 'Unnamed: 134', 'Unnamed: 135', 'Unnamed: 136', 'Unnamed: 137', 'IWF US Equity', 'Unnamed: 139', 'Unnamed: 140', 'Unnamed: 141', 'Unnamed: 142', 'Unnamed: 143', 'IWD US Equity', 'Unnamed: 145', 'Unnamed: 146', 'Unnamed: 147', 'Unnamed: 148', 'Unnamed: 149', 'MTUM US Equity', 'Unnamed: 151', 'Unnamed: 152', 'Unnamed: 153', 'Unnamed: 154', 'Unnamed: 155', 'QUAL US Equity', 'Unnamed: 157', 'Unnamed: 158', 'Unnamed: 159', 'Unnamed: 160', 'Unnamed: 161', 'GLD US Equity', 'Unnamed: 163', 'Unnamed: 164', 'Unnamed: 165', 'Unnamed: 166', 'Unnamed: 167', 'SLV US Equity', 'Unnamed: 169', 'Unnamed: 170', 'Unnamed: 171', 'Unnamed: 172', 'Unnamed: 173', 'VIX Index', 'Unnamed: 175', 'Unnamed: 176', 'Unnamed: 177', 'Unnamed: 178']

In [6]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

df_raw.head(20)

,SPY US Equity,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,QQQ US Equity,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,IWM US Equity,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,DIA US Equity,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,VTI US Equity,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,XLB US Equity,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,XLE US Equity,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,XLF US Equity,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,XLI US Equity,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,XLK US Equity,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,XLP US Equity,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,XLU US Equity,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,XLV US Equity,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,XLY US Equity,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,XLRE US Equity,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,SHY US Equity,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,IEF US Equity,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,TLT US Equity,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,TIP US Equity,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,LQD US Equity,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,HYG US Equity,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,EFA US Equity,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,EEM US Equity,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,IWF US Equity,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,IWD US Equity,Unnamed: 145,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,MTUM US Equity,Unnamed: 151,Unnamed: 152,Unnamed: 153,Unnamed: 154,Unnamed: 155,QUAL US Equity,Unnamed: 157,Unnamed: 158,Unnamed: 159,Unnamed: 160,Unnamed: 161,GLD US Equity,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,SLV US Equity,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,VIX Index,Unnamed: 175,Unnamed: 176,Unnamed: 177,Unnamed: 178
0,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume,NaN,Dates,Last Price,Bid Price,Ask Price,Volume
1,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN,NaN,01/01/2010,NaN,NaN,NaN,NaN
2,04/01/2010,113.33,NaN,NaN,118944541,NaN,04/01/2010,46.42,NaN,NaN,62822798,NaN,04/01/2010,63.98,NaN,NaN,42866134,NaN,04/01/2010,105.66,NaN,NaN,8981390,NaN,04/01/2010,57.31,56.95,57.8,2251561,NaN,04/01/2010,17.01,NaN,NaN,15134996,NaN,04/01/2010,29.405,29.165,29.62,33856894,NaN,04/01/2010,11.9285,11.8798,11.9204,75511478,NaN,04/01/2010,28.32,28.07,28.52,7471436,NaN,04/01/2010,11.635,11.53,11.715,16899350,NaN,04/01/2010,26.67,26.5,26.88,8465873,NaN,04/01/2010,15.54,15.49,15.675,16435092,NaN,04/01/2010,31.61,31.6,31.84,5580847,NaN,04/01/2010,15,NaN,NaN,10887658,NaN,04/01/2010,NaN,NaN,NaN,NaN,NaN,04/01/2010,83.07,82.04,NaN,1220569,NaN,04/01/2010,88.82,87.72,90.25,619066,NaN,04/01/2010,89.81,89.4,90.2,2829018,NaN,04/01/2010,104.17,103.82,105.48,3583125,NaN,04/01/2010,104.7,103.52,105.48,2017559,NaN,04/01/2010,88.53,NaN,NaN,1316863,NaN,04/01/2010,56.73,NaN,NaN,18556962,NaN,04/01/2010,42.71,NaN,NaN,70764962,NaN,04/01/2010,50.5,NaN,NaN,3390756,NaN,04/01/2010,58.52,NaN,NaN,2371780,NaN,04/01/2010,NaN,NaN,NaN,NaN,NaN,04/01/2010,NaN,NaN,NaN,NaN,NaN,04/01/2010,109.8,NaN,NaN,16224044,NaN,04/01/2010,17.23,17,17.35,9720405,NaN,04/01/2010,20.04,NaN,NaN,NaN
3,05/01/2010,113.63,NaN,NaN,111579866,NaN,05/01/2010,46.42,NaN,NaN,62935591,NaN,05/01/2010,63.76,NaN,NaN,55523671,NaN,05/01/2010,105.49,NaN,NaN,6551727,NaN,05/01/2010,57.53,57.18,57.83,1597643,NaN,05/01/2010,17.065,NaN,NaN,17678308,NaN,05/01/2010,29.645,29.61,29.675,34737792,NaN,05/01/2010,12.1478,12.0016,12.1397,78614535,NaN,05/01/2010,28.42,28.21,28.56,8256635,NaN,05/01/2010,11.62,11.49,11.735,39976404,NaN,05/01/2010,26.68,26.48,26.96,11805325,NaN,05/01/2010,15.355,15.26,15.39,36048758,NaN,05/01/2010,31.3,31.08,31.73,5428534,NaN,05/01/2010,15.055,NaN,NaN,12324256,NaN,05/01/2010,NaN,NaN,NaN,NaN,NaN,05/01/2010,83.17,82.54,NaN,598187,NaN,05/01/2010,89.21,88.56,89.55,1547485,NaN,05/01/2010,90.39,90.26,90.6,2841589,NaN,05/01/2010,104.51,103.77,105.46,1738199,NaN,05/01/2010,105.2,104.42,106.2,1143757,NaN,05/01/2010,88.95,88.74,NaN,732904,NaN,05/01/2010,56.78,NaN,NaN,14352716,NaN,05/01/2010,43.02,NaN,NaN,50199062,NaN,05/01/2010,50.51,NaN,NaN,2202150,NaN,05/01/2010,58.87,NaN,NaN,1867976,NaN,05/01/2010,NaN,NaN,NaN,NaN,NaN,05/01/2010,NaN,NaN,NaN,NaN,NaN,05/01/2010,109.7,NaN,NaN,14213049,NaN,05/01/2010,17.51,17.47,17.49,13324963,NaN,05/01/2010,19.35,NaN,NaN,NaN
4,06/01/2010,113.71,NaN,NaN,116074402,NaN,06/01/2010,46.14,NaN,NaN,96033002,NaN,06/01/2010,63.7,63.71,63.79,59713818,NaN,06/01/2010,105.56,105.52,105.59,6799151,NaN,06/01/2010,57.61,57.35,57.94,2120206,NaN,06/01/2010,17.355,NaN,NaN,16183884,NaN,06/01/2010,30,29.975,30.015,48703650,NaN,06/01/2010,12.1721,12.1478,12.1803,61330199,NaN,06/01/2010,28.48,27.65,28.56,5356668,NaN,06/01/2010,11.49,11.43,11.565,20048028,NaN,06/01/2010,26.66,25.85,27.03,9267001,NaN,06/01/2010,15.445,15.4,15.545,25490112,NaN,06/01/2010,31.62,31.38,33.54,4883537,NaN,06/01/2010,15.075,NaN,NaN,8493668,NaN,06/01/2010,NaN,NaN,NaN,NaN,NaN,06/01/2010,83.18,81.26,NaN,1534890,NaN,06/01/2010,88.85,87.22,90.25,365423,NaN,06/01/2010,89.18,88.31,90.2,4099754,NaN,06/01/2010,104.24,104.15,107.36,1233884,NaN,06/01/2010,104.89,103.52,105.48,1005499,NaN,06/01/2010,89.18,89.08,NaN,715700,NaN,06/01/2010,57.02,NaN,NaN,11888100,NaN,06/01/2010,43.11,43.12,43.33,50670650,NaN,06/01/2010,50.51,50.19,50.83,3259269,NaN,06/01/2010,59.07,58.84,59.46,1815234,NaN,06/01/2010,NaN,NaN,NaN,NaN,NaN,06/01/2010,NaN,NaN,NaN,NaN,NaN,06/01/2010,111.51,111.28,111.54,24990473,NaN,06/01/2010,17.86,17.91,18.13,14046940,NaN,06/01/2010,19.16,NaN,NaN,NaN
5,07/01/2010,114.19,NaN,NaN,131091048,NaN,07/01/2010,46.17,NaN,NaN,77095132,NaN,07/01/2010,64.17,NaN,NaN,56123822,NaN,07/01/2010,105.94,NaN,NaN,6313467,NaN,07/01/2010,57.85,56.78,58.33,1656639,NaN,07/01/2010,17.22,NaN,NaN,11514412,NaN,07/01/2010,29.955,29.9,30.54,34900472,NaN,07/01/2010,12.432,12.4401,12.4969,95757300,NaN,07/01/2010,28.79,28.74,29.18,12118130,NaN,07/01/2010,11.445,11.42,11.495,14586252,NaN,07/01/2010,26.66,26.19,27.28,6951486,NaN,07/01/2010,15.375,15.375,15.56,13126098,NaN,07/01/2010,31.73,31.12,33.66,6114696,NaN,07/01/2010,15.2,NaN,NaN,11473240,NaN,07/01/2010,NaN,NaN,NaN,NaN,NaN,07/01/2010,83.16,81.28,NaN,771940,NaN,07/01/2010,88.85,87.03,90.25,390882,NaN,07/01/2010,89.33,87.46,89.65,2794417,NaN,07/01/2010,104.4,104.4,107.29,982093,NaN,07/01/2010,105.02,103.52,105.48,1264091,NaN,07/01/2010,89.54,NaN,NaN,955915,NaN,07/01/2010,56.8,NaN,NaN,10906600,NaN,07/01/2010,42.86,NaN,NaN,41803892,NaN,07/01/2010,50.55,49.38,51.21,2928922,NaN,07/01/2010,59.57,59.06,59.92,2525961,NaN,07/01/2010,NaN,NaN,NaN,NaN,NaN,07/01/2010,NaN,NaN,NaN,NaN,NaN,07/01/2010,110.82,NaN,NaN,13609730,NaN,07/01/2010,17.89,17.79,17.81,12587171,NaN,07/01/2010,19.06,NaN,NaN,NaN
6,08/01/2010,114.57,NaN,NaN,126402764,NaN,08/01/2010,46.55,NaN,NaN,88886598,NaN,08/01/2010,64.52,NaN,NaN,48811778,NaN,08/01/2010,106.11,NaN,NaN,4912227,NaN,08/01/2010,58.04,57.8,58.68,1650019,NaN,08/01/2010,17.46,NaN,NaN,9284704,NaN,08/01/2010,30.15,NaN,NaN,26690080,NaN,08/01/2010,12.3589,NaN,NaN,90883177,NaN,08/01/2010,29.25,29.1,29.3,8064908,NaN,08/01/2010,11.52,11.49,11.57,23773318,NaN,08/01/2010,26.57,25.77,26.58,5437373,NaN,08/01/2010,15.36,15.35,15.51,12535166,NaN,08/01/2010,31.78,31.56,32.68,4284802,NaN,08/01/2010,15.195,NaN,NaN,12875956,NaN,08/01/2010,NaN,NaN,NaN,NaN,NaN,08/01/2010,83.2398,81.34,NaN,713128,NaN,08/01/2010,88.96,NaN,NaN,382435,NaN,08/01/2010,89.29,NaN,NaN,2910649,NaN,08/01/2010,104.62,104,107.55,866637,NaN,08/01/2010,105.25,103.52,105.48,704539,NaN,08/01/2010,89.68,NaN,NaN,711371,NaN,08/01/2010,57.25,NaN,NaN,12826466,NaN,08/01/2010,43.2,NaN,NaN,41121651,NaN,08/01/2010,50.83,NaN,NaN,2913896,NaN,08/01/2010,59.71,NaN,NaN,1514511,NaN,08/01/2010,NaN,NaN,NaN,NaN,NaN,08/01/2010,NaN,NaN,NaN,NaN,NaN,08/01/2010,111.37,NaN,NaN,15896296,NaN,08/01/2010,18.15,NaN,NaN,11737678,NaN,08/01/2010,18.13,NaN,NaN,NaN
7,11/01/2010,114.73,NaN,NaN,106375678,NaN,11/01/2010,46.36,NaN,NaN,104673315,NaN,11/01/2010,64.26,NaN,NaN,51638883,NaN,11/01/2010,106.54,NaN,NaN,6858294,NaN,11/01/2010,58.12,57.55,58.08,1883013,NaN,11/01/2010,17.365,NaN,NaN,18217632,NaN,11/01/2010,30.11,NaN,NaN,38921742,NaN,11/01/2010,12.367,NaN,NaN,59106020,NaN,11/01/2010,29.57,29.33,29.66,11895509,NaN,11/01/2010,11.475,11.42,11.45,30482662,NaN,11/01/2010,26.64,26.46,26.65,6140142,NaN,11/01/2010,15.52,15.465,15.59,17749088,NaN,11/01/2010,31.96,31.41,32.42,4177636,NaN,11/01/2010,15.165,NaN,NaN,8346882,NaN,11/01/2010,NaN,NaN,NaN,NaN,NaN,11/01/2010,83.28,83.18,83.43,756540,NaN,11/01/2010,89.02,NaN,NaN,653508,NaN,11/01/2010,88.8,NaN,NaN,2182206,NaN,11/01/2010,104.39,104.2,107.56,1076650,NaN,11/01/2010,105.36,104.9,105.48,817910,NaN,11/01/2010,89.6,NaN,NaN,895770,NaN,11/01/2010,57.72,NaN,NaN,12388069,NaN,11/01/2010,43.11,NaN,NaN,42549247,NaN,11/01/2010,50.74,NaN,NaN,2361830,NaN,11/01/2010,59.85,NaN,NaN,2151660,NaN,11/01/2010,NaN,NaN,NaN,NaN,NaN,11/01/2010,NaN,NaN,NaN,NaN,NaN,11/01/2010,112.85,NaN,NaN,17252989,NaN,11/01/2010,18.21,NaN,NaN,19132220,NaN,11/01/2010,17.55,NaN,NaN,NaN
8,12/01/2010,113.66,NaN,NaN,163333432,NaN,12/01/2010,45.78,NaN,NaN,90673830,NaN,12/01/2010,63.56,NaN,NaN,45855860,NaN,12/01/2010,106.14,NaN,NaN,8875465,NaN,12/01/2010,57.52,57.12,57.99,1730026,NaN,12/01/2010,17.035,NaN,NaN,26324298,NaN,12/01/2010,29.675,29.625,29.8,43021602,NaN,12/01/2010,12.1884,12.1721,12.2777,111794556,NaN,12/01/2010,29.33,29.06,29.43,12020671,NaN,12/01/2010,11.35,11.35,11.445,19485766,NaN,12/01/2010,26.79,26.7,26.98,6822390,NaN,12/01/2010,15.455,15.34,15.585,16654974,NaN,12/01/2010,31.73,31.46,31.95,5791359,NaN,12/01/2010,14.97,NaN,NaN,10946618,NaN,12/01/2010,NaN,NaN,NaN,NaN,NaN,12/01/2010,83.35,81.43,NaN,582839,NaN,12/01/2010,89.66,88.08,90.3,402980,NaN,12/01/2010,90.32,NaN,NaN,4321155,NaN,12/01/2010,104.87,104.26,NaN,1072999,NaN,12/01/2010,105.56,104.9,106.48,1343070,NaN,12/01/2010,89.14,NaN,NaN,1133841,NaN,12/01/2010,57.04,NaN,NaN,19030429,NaN,12/01/2010,42.42,NaN,NaN,65902562,NaN,12/01/2010,50.32,NaN,NaN,2229441,NaN,12/01/2010,59.06,NaN,NaN,2107787,NaN,12/01/2010,NaN,NaN,NaN,NaN,NaN,12/01/2010,NaN,NaN,NaN,NaN,NaN,12/01/2010,110.49,NaN,NaN,29182550,NaN,12/01/2010,17.91,NaN,NaN,13602604,NaN,12/01/2010,18.25,NaN,NaN,NaN
9,13/01/2010,114.62,NaN,NaN,161821927,NaN,13/01/2010,46.35,NaN,NaN,100661457,NaN,13/01/2010,64.38,NaN,NaN,39504156,NaN,13/01/2010,106.75,NaN,NaN,8620253,NaN,13/01/2010,58.06,57.69,58.34,1825157,NaN,13/01/2010,17.235,NaN,NaN,23886180,NaN,13/01/2010,29.785,29.8,29.84,44275614,NaN,13/01/2010,12.3264,12.3021,12.4076,81923818,NaN,13/01/2010,29.45,29.17,29.72,10978199,NaN,13/01/2010,11.46,11.45,11.505,20107266,NaN,13/01/2010,26.98,26.7,27.21,7926687,NaN,13/01/2010,15.625,15.475,15.725,15718858,NaN,13/01/2010,32.15,31.86,32.39,8056066,NaN,13/01/2010,15.14,NaN,NaN,9231598,NaN,13/01/2010,NaN,NaN,NaN,NaN,NaN,13/01/2010,83.28,NaN,NaN,590422,NaN,13/01/2010,89.23,NaN,NaN,281884,NaN,13/01/2010,89.27,89.2,92.19,4754916,NaN,13/01/2010,104.4,104.3,NaN,1187484,NaN,13/01/2010,105.12,104.52,106.48,1090621,NaN,13/01/2010,89.34,NaN,NaN,868832,NaN,13/01/2010,57.52,NaN,NaN,15446666,NaN,13/01/2010,42.55,NaN,NaN,48040175,NaN,13/01/2010,50.84,50.52,51.1,2228343,NaN,13/01/2010,59.6,59.27,59.99,2535403,NaN,13/01/2010,NaN,NaN,NaN,NaN,NaN,13/01/2010,NaN,NaN,NaN,NaN,NaN,13/01/2010,111.54,112.01,112.06,20013968,NaN,13/01/2010,18.27,18.31,18.34,15457866,NaN,13/01/2010,17.85,NaN,NaN,NaN
10,14/01/2010,114.93,NaN,NaN,115783759,NaN,14/01/2010,46.39,NaN,NaN,75812668,NaN,14/01/2010,64.62,NaN,NaN,41868876,NaN,14/01/2010,107.03,NaN,NaN,7040619,NaN,14/01/2010,58.16,58.22,59.05,1667014,NaN,14/01/2010,17.025,NaN,NaN,19230984,NaN,14/01/2010,29.87,NaN,NaN,31090684,NaN,14/01/2010,12.3833,NaN,NaN,57567778,NaN,14/01/2010,29.45,29.3,29.72,4762646,NaN,14/01/2010,11.49,11.53,11.635,15017200,NaN,14/01/2010,26.9,26.48,27.32,5258856,NaN,14/01/2010,15.555,15.335,15.725,9633142,NaN,14/01/2010,32.44,32.18,32.92,7801316,NaN,14/01/2010,15.14,NaN,NaN,11280584,NaN,14/01/2010,NaN,NaN,NaN,NaN,NaN,14/01/2010,83.36,81.43,NaN,549900,NaN,14/01/2010,89.65,88.08,89.89,511642,NaN,14/01/2010,90.52,NaN,NaN,4188789,NaN,14/01/2010,104.67,104.38,105,1495817,NaN,14/01/2010,105.5,104.52,106.48,873178,NaN,14/01/2010,89.44,NaN,NaN,394524,NaN,14/01/2010,57.96,NaN,NaN,13362560,NaN,14/01/2010,42.44,NaN,NaN,52894279,NaN,14/01/2010,50.96,NaN,NaN,1492420,NaN,14/01/2010,59.81,NaN,NaN,1735903,NaN,14/01/2010,NaN,NaN,NaN,NaN,NaN,14/01/2010,NaN,NaN,NaN,NaN,NaN,14/01/2010,112.03,NaN,NaN,18316938,NaN,14/01/2010,18.31,NaN,NaN,8813402,NaN,14/01/2010,17.63,NaN,NaN,NaN
11,15/01/2010,113.64,NaN,NaN,212283097,NaN,15/01/2010,45.85,NaN,NaN,126866066,NaN,15/01/2010,63.68,NaN,NaN,68728703,NaN,15/01/2010,106.01,NaN,NaN,14028756,NaN,15/01/2010,57.5,57.22,58.02,2787124,NaN,15/01/2010,16.9,NaN,NaN,15210490,NaN,15/01/2010,29.63,29.53,29.895,38111838,NaN,15/01/2010,12.1315,12.1072,12.1315,95911809,NaN,15/01/2010,29.07,28.93,29.19,7250950,NaN,15/01/2010,11.33,11.225,11.46,27066514,NaN,15/01/2010,26.77,26.77,26.88,11968743,NaN,15/01/2010,15.455,15.295,15.61,25421250,NaN,15/01/2010,32.22,31.92,32.36,9692305,NaN,15/01/2010,14.99,NaN,NaN,11778860,NaN,15/01/2010,NaN,NaN,NaN,NaN,NaN,15/01/2010,83.43,82.82,NaN,648213,NaN,15/01/2010,90.05,89.36,90.81,429130,NaN,15/01/2010,91.08,91,91.36,4142729,NaN,15/01/2010,105.01,104.52,105.78,1254552,NaN,15/01/2010,105.46,104.68,106.3,834221,NaN,15/01/2010,89.08,88.81,89.4,835280,NaN,15/01/2010,57.05,NaN,NaN,19281665,NaN,15/01/2010,41.9493,NaN,NaN,76689365,NaN,15/01/2010,50.45,50.04,50.87,1957380,NaN,15/01/2010,59.01,NaN,NaN,2211436,NaN,15/01/2010,NaN,NaN,NaN,NaN,NaN,15/01/2010,NaN,NaN,NaN,NaN,NaN,15/01/2010,110.86,NaN,NaN,18008047,NaN,15/01/2010,18.05,17.98,18.06,9981460,NaN,15/01/2010,17.91,NaN,NaN,NaN
12,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN,NaN,18/01/2010,NaN,NaN,NaN,NaN
13,19/01/2010,115.06,115.05,115.14,139172635,NaN,19/01/2010,46.59,NaN,NaN,84388146,NaN,19/01/2010,64.85,64.65,64.95,46843619,NaN,19/01/2010,107.17,107.13,107.19,10881108,NaN,19/01/2010,58.26,57.8,58.75,2546626,NaN,19/01/2010,17.17,16.975,17.32,13603278,NaN,19/01/2010,29.9,29.9,29.96,29226366,NaN,19/01/2010,12.2858,12.2696,12.3021,81590334,NaN,19/01/2010,29.39,29.1,29.57,11941276,NaN,19/01/2010,11.525,11.27,11.495,14965492,NaN,19/01/2010,26.93,26.8,27.22,10974120,NaN,19/01/2010,15.635,15.465,15.64,11794744,NaN,19/01/2010,33,32.62,33.44,17753701,NaN,19/01/2010,15.19,15.145,15.33,8836914,NaN,19/01/2010,NaN,NaN,NaN,NaN,NaN,19/01/2010,83.45,83.29,83.56,1153947,NaN,19/01/2010,89.89,89.76,90.06,411813,NaN,19/01/2010,90.82,90.2,91.58,2496039,NaN,19/01/2010,104.93,104.71,105.76,1649667,NaN,19/01/2010,105.55,104.64,106.37,822095,NaN,19/01/2010,89.118,88.4,89.23,796891,NaN,19/01/2010,57.61,57.16,57.55,17507629,NaN,19/01/2010,42.8,42.42,42.88,57600926,NaN,19/01/2010,51,50.63,51.46,2957091,NaN,19/01/2010,59.62,59.29,60.24,2604035,NaN,19/01/2010,NaN,NaN,NaN,NaN,NaN,19/01/2010,NaN,NaN,NaN,NaN,NaN,19/01/2010,111.52,111.82,111.85,10474427,NaN,19/01/2010,18.45,18.47,18.49,8643436,NaN,19/01/2010,17.58,NaN,NaN,NaN
14,20/01/2010,113.89,NaN,NaN,216490121,NaN,20/01/2010,45.92,NaN,NaN,145680408,NaN,20/01/2010,63.91,63.38,64.5,62485001,NaN,20/01/2010,106.02,105.98,106.15,11904459,NaN,20/01/2010,57.72,57.38,58.03,2755045,NaN,20/01/2010,16.865,16.77,16.94,23007494,NaN,20/01/2010,29.435,29.475,29.675,31283516,NaN,20/01/2010,12.2533,12.2696,12.3264,80714387,NaN,20/01/2010,28.94,28.86,29.01,9810349,NaN,20/01/2010,11.34,11.27,11.395,29397904,NaN,20/01/2010,26.73,26.68,26.94,8670404,NaN,20/01/2010,15.47,15.35,15.595,19039362,NaN,20/01/2010,32.72,32.49,32.88,16706113,NaN,20/01/2010,14.985,14.9,15.115,10056200,NaN,20/01/2010,NaN,NaN,NaN,NaN,NaN,20/01/2010,83.45,83.29,NaN,1085527,NaN,20/01/2010,90.2,89.38,91.1,228795,NaN,20/01/2010,91.74,91.66,92.19,2800568,NaN,20/01/2010,105.09,104.77,106.06,1020422,NaN,20/01/2010,105.48,104.69,105.78,1111920,NaN,20/01/2010,88.99,88.71,NaN,588443,NaN,20/01/2010,56.14,55.8,56.49,24510047,NaN,20/01/2010,41.77,41.77,42.05,78940180,NaN,20/01/2010,50.55,50.2,50.83,3089148,NaN,20/01/2010,59.19,58.9,59.57,2257721,NaN,20/01/2010,NaN,NaN,NaN,NaN,NaN,20/01/2010,NaN,NaN,NaN,NaN,NaN,20/01/2010,108.94,108.91,109.23,17539029,NaN,20/01/2010,17.57,17.43,17.74,18988516,NaN,20/01/2010,18.68,NaN,NaN,NaN

In [7]:
df_raw.dtypes

SPY US Equity       str
Unnamed: 1       object
Unnamed: 2       object
Unnamed: 3       object
Unnamed: 4       object
                  ...
VIX Index           str
Unnamed: 175     object
Unnamed: 176        str
Unnamed: 177        str
Unnamed: 178        str
Length: 179, dtype: object

In [9]:
possible_date_cols = [c for c in df_raw.columns if "Dates" in c.lower()]
possible_date_cols

[]